//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Data;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Mapping;

namespace cms.dbase.models
{
	/// <summary>
	/// Database       : Malyshok21
	/// Data Source    : chuvashia.com
	/// Server Version : 11.00.3000
	/// </summary>
	public partial class CMSdb : LinqToDB.Data.DataConnection
	{
		public ITable<cms_content_sv_people_posts>          cms_content_sv_people_postss          { get { return this.GetTable<cms_content_sv_people_posts>(); } }
		public ITable<cms_log>                              cms_logs                              { get { return this.GetTable<cms_log>(); } }
		public ITable<cms_log_actions>                      cms_log_actionss                      { get { return this.GetTable<cms_log_actions>(); } }
		public ITable<cms_log_sections>                     cms_log_sectionss                     { get { return this.GetTable<cms_log_sections>(); } }
		public ITable<cms_menu>                             cms_menus                             { get { return this.GetTable<cms_menu>(); } }
		public ITable<cms_menu_group>                       cms_menu_groups                       { get { return this.GetTable<cms_menu_group>(); } }
		public ITable<cms_resolutions>                      cms_resolutionss                      { get { return this.GetTable<cms_resolutions>(); } }
		public ITable<cms_resolutions_templates>            cms_resolutions_templatess            { get { return this.GetTable<cms_resolutions_templates>(); } }
		public ITable<cms_sites>                            cms_sitess                            { get { return this.GetTable<cms_sites>(); } }
		public ITable<cms_sites_domains>                    cms_sites_domainss                    { get { return this.GetTable<cms_sites_domains>(); } }
		public ITable<cms_sv_log>                           cms_sv_logs                           { get { return this.GetTable<cms_sv_log>(); } }
		public ITable<cms_sv_log_users>                     cms_sv_log_userss                     { get { return this.GetTable<cms_sv_log_users>(); } }
		public ITable<cms_sv_resolutions>                   cms_sv_resolutionss                   { get { return this.GetTable<cms_sv_resolutions>(); } }
		public ITable<cms_sv_resolutions_templates>         cms_sv_resolutions_templatess         { get { return this.GetTable<cms_sv_resolutions_templates>(); } }
		public ITable<cms_sv_user_sites>                    cms_sv_user_sitess                    { get { return this.GetTable<cms_sv_user_sites>(); } }
		public ITable<cms_sv_users>                         cms_sv_userss                         { get { return this.GetTable<cms_sv_users>(); } }
		public ITable<cms_user_site_link>                   cms_user_site_links                   { get { return this.GetTable<cms_user_site_link>(); } }
		public ITable<cms_users>                            cms_userss                            { get { return this.GetTable<cms_users>(); } }
		public ITable<cms_users_group>                      cms_users_groups                      { get { return this.GetTable<cms_users_group>(); } }
		public ITable<content_banner_sections>              content_banner_sectionss              { get { return this.GetTable<content_banner_sections>(); } }
		public ITable<content_banners>                      content_bannerss                      { get { return this.GetTable<content_banners>(); } }
		public ITable<content_content_link>                 content_content_links                 { get { return this.GetTable<content_content_link>(); } }
		public ITable<content_documents>                    content_documentss                    { get { return this.GetTable<content_documents>(); } }
		public ITable<content_materials>                    content_materialss                    { get { return this.GetTable<content_materials>(); } }
		public ITable<content_materials_groups>             content_materials_groupss             { get { return this.GetTable<content_materials_groups>(); } }
		public ITable<content_materials_groups_link>        content_materials_groups_links        { get { return this.GetTable<content_materials_groups_link>(); } }
		public ITable<content_photoalbum>                   content_photoalbums                   { get { return this.GetTable<content_photoalbum>(); } }
		public ITable<content_photos>                       content_photoss                       { get { return this.GetTable<content_photos>(); } }
		public ITable<content_sitemap>                      content_sitemaps                      { get { return this.GetTable<content_sitemap>(); } }
		public ITable<content_sitemap_menus>                content_sitemap_menuss                { get { return this.GetTable<content_sitemap_menus>(); } }
		public ITable<content_sitemap_menutypes>            content_sitemap_menutypess            { get { return this.GetTable<content_sitemap_menutypes>(); } }
		public ITable<content_sv_banner_sections_sites>     content_sv_banner_sections_sitess     { get { return this.GetTable<content_sv_banner_sections_sites>(); } }
		public ITable<content_sv_banners_section>           content_sv_banners_sections           { get { return this.GetTable<content_sv_banners_section>(); } }
		public ITable<content_sv_materials_groups>          content_sv_materials_groupss          { get { return this.GetTable<content_sv_materials_groups>(); } }
		public ITable<content_sv_materials_groups_for_site> content_sv_materials_groups_for_sites { get { return this.GetTable<content_sv_materials_groups_for_site>(); } }
		public ITable<content_sv_materials_sites>           content_sv_materials_sitess           { get { return this.GetTable<content_sv_materials_sites>(); } }
		public ITable<content_sv_orgs_by_type>              content_sv_orgs_by_types              { get { return this.GetTable<content_sv_orgs_by_type>(); } }
		public ITable<content_sv_orgs_not_attached>         content_sv_orgs_not_attacheds         { get { return this.GetTable<content_sv_orgs_not_attached>(); } }
		public ITable<content_sv_people_department>         content_sv_people_departments         { get { return this.GetTable<content_sv_people_department>(); } }
		public ITable<content_sv_people_front>              content_sv_people_fronts              { get { return this.GetTable<content_sv_people_front>(); } }
		public ITable<content_sv_people_org>                content_sv_people_orgs                { get { return this.GetTable<content_sv_people_org>(); } }
		public ITable<content_sv_sitemap_menu>              content_sv_sitemap_menus              { get { return this.GetTable<content_sv_sitemap_menu>(); } }
		public ITable<front_modules>                        front_moduless                        { get { return this.GetTable<front_modules>(); } }
		public ITable<front_page_views>                     front_page_viewss                     { get { return this.GetTable<front_page_views>(); } }
		public ITable<front_section>                        front_sections                        { get { return this.GetTable<front_section>(); } }
		public ITable<front_site_section>                   front_site_sections                   { get { return this.GetTable<front_site_section>(); } }
		public ITable<front_sv_page_veiw>                   front_sv_page_veiws                   { get { return this.GetTable<front_sv_page_veiw>(); } }
		public ITable<sv_orgs_materials>                    sv_orgs_materialss                    { get { return this.GetTable<sv_orgs_materials>(); } }
		public ITable<sv_sites_banners>                     sv_sites_bannerss                     { get { return this.GetTable<sv_sites_banners>(); } }

		public CMSdb()
			: base("CMSdb")
		{
			InitDataContext();
		}

		public CMSdb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		#region Table Functions

		#region SF_SplitString

		[Sql.TableFunction(Schema="dbo", Name="SF_SplitString")]
		public ITable<SF_SplitStringResult> SF_SplitString(string @List, char? @Splitter)
		{
			return this.GetTable<SF_SplitStringResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(),
				@List,
				@Splitter);
		}

		public partial class SF_SplitStringResult
		{
			public int    ID { get; set; }
			public string V  { get; set; }
		}

		#endregion

		#region SF_UserResolutions

		[Sql.TableFunction(Schema="dbo", Name="SF_UserResolutions")]
		public ITable<SF_UserResolutionsResult> SF_UserResolutions(string @Url, Guid? @User)
		{
			return this.GetTable<SF_UserResolutionsResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(),
				@Url,
				@User);
		}

		public partial class SF_UserResolutionsResult
		{
			public bool? B_Read   { get; set; }
			public bool? B_Write  { get; set; }
			public bool? B_Change { get; set; }
			public bool? B_Delete { get; set; }
		}

		#endregion

		#endregion

		#region FreeTextTable

		public class FreeTextKey<T>
		{
			public T   Key;
			public int Rank;
		}

		[FreeTextTableExpression]
		public ITable<FreeTextKey<TKey>> FreeTextTable<TTable,TKey>(string field, string text)
		{
			return this.GetTable<FreeTextKey<TKey>>(
				this,
				((MethodInfo)(MethodBase.GetCurrentMethod())).MakeGenericMethod(typeof(TTable), typeof(TKey)),
				field,
				text);
		}

		[FreeTextTableExpression]
		public ITable<FreeTextKey<TKey>> FreeTextTable<TTable,TKey>(Expression<Func<TTable,string>> fieldSelector, string text)
		{
			return this.GetTable<FreeTextKey<TKey>>(
				this,
				((MethodInfo)(MethodBase.GetCurrentMethod())).MakeGenericMethod(typeof(TTable), typeof(TKey)),
				fieldSelector,
				text);
		}

		#endregion
	}

	// View
	[Table(Schema="dbo", Name="cms_content_sv_people_posts")]
	public partial class cms_content_sv_people_posts
	{
		[Column, NotNull    ] public Guid   id           { get; set; } // uniqueidentifier
		[Column, NotNull    ] public int    f_post       { get; set; } // int
		[Column,    Nullable] public string c_surname    { get; set; } // varchar(64)
		[Column,    Nullable] public string c_name       { get; set; } // varchar(64)
		[Column,    Nullable] public string c_patronymic { get; set; } // varchar(64)
	}

	[Table(Schema="dbo", Name="cms_log")]
	public partial class cms_log
	{
		[PrimaryKey, NotNull    ] public Guid     id          { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public Guid     f_page      { get; set; } // uniqueidentifier
		[Column,        Nullable] public string   c_page_name { get; set; } // nvarchar(512)
		[Column,        Nullable] public string   f_site      { get; set; } // varchar(64)
		[Column,        Nullable] public string   f_section   { get; set; } // varchar(64)
		[Column,     NotNull    ] public Guid     f_user      { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public DateTime d_date      { get; set; } // datetime
		[Column,     NotNull    ] public string   f_action    { get; set; } // varchar(32)
		[Column,     NotNull    ] public string   c_ip        { get; set; } // varchar(16)

		#region Associations

		/// <summary>
		/// FK_log_actions
		/// </summary>
		[Association(ThisKey="f_action", OtherKey="c_action", CanBeNull=false, KeyName="FK_log_actions", BackReferenceName="logactionss")]
		public cms_log_actions logactions { get; set; }

		/// <summary>
		/// FK_cms_log_sections
		/// </summary>
		[Association(ThisKey="f_section", OtherKey="c_alias", CanBeNull=true, KeyName="FK_cms_log_sections", BackReferenceName="cmslogsectionss")]
		public cms_log_sections cmslogsections { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_log_actions")]
	public partial class cms_log_actions
	{
		[PrimaryKey, NotNull] public string c_action      { get; set; } // varchar(32)
		[Column,     NotNull] public string c_action_name { get; set; } // varchar(256)

		#region Associations

		/// <summary>
		/// FK_log_actions_BackReference
		/// </summary>
		[Association(ThisKey="c_action", OtherKey="f_action", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_log> logactionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_log_sections")]
	public partial class cms_log_sections
	{
		[PrimaryKey, NotNull] public string c_alias        { get; set; } // varchar(64)
		[Column,     NotNull] public string c_section_name { get; set; } // varchar(64)

		#region Associations

		/// <summary>
		/// FK_cms_log_sections_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_section", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_log> cmslogsectionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_menu")]
	public partial class cms_menu
	{
		[PrimaryKey, NotNull    ] public Guid     id       { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public int      n_permit { get; set; } // int
		[Column,        Nullable] public string   c_alias  { get; set; } // varchar(16)
		[Column,     NotNull    ] public string   c_title  { get; set; } // nvarchar(128)
		[Column,        Nullable] public string   c_desc   { get; set; } // nvarchar(1024)
		[Column,     NotNull    ] public DateTime d_date   { get; set; } // datetime
		[Column,        Nullable] public string   c_class  { get; set; } // varchar(50)
		[Column,        Nullable] public string   f_group  { get; set; } // varchar(16)

		#region Associations

		/// <summary>
		/// FK_cms_menu_group
		/// </summary>
		[Association(ThisKey="f_group", OtherKey="c_alias", CanBeNull=true, KeyName="FK_cms_menu_group", BackReferenceName="cmsmenugroups")]
		public cms_menu_group cmsmenugroup { get; set; }

		/// <summary>
		/// fk_menu_template_resolutions_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_menu_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_resolutions_templates> fkmenutemplateresolutionss { get; set; }

		/// <summary>
		/// fk_menu_resolutions_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="c_menu_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_resolutions> fkmenuresolutionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_menu_group")]
	public partial class cms_menu_group
	{
		[Identity               ] public int    num     { get; set; } // int
		[Column,        Nullable] public string c_title { get; set; } // varchar(32)
		[PrimaryKey, NotNull    ] public string c_alias { get; set; } // varchar(16)

		#region Associations

		/// <summary>
		/// FK_cms_menu_group_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_menu> cmsmenugroups { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_resolutions")]
	public partial class cms_resolutions
	{
		[PrimaryKey, Identity] public int  id          { get; set; } // int
		[Column,     NotNull ] public Guid c_menu_id   { get; set; } // uniqueidentifier
		[Column,     NotNull ] public Guid c_user_id   { get; set; } // uniqueidentifier
		[Column,     NotNull ] public bool b_read      { get; set; } // bit
		[Column,     NotNull ] public bool b_write     { get; set; } // bit
		[Column,     NotNull ] public bool b_change    { get; set; } // bit
		[Column,     NotNull ] public bool b_delete    { get; set; } // bit
		[Column,     NotNull ] public bool b_importent { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_menu_resolutions
		/// </summary>
		[Association(ThisKey="c_menu_id", OtherKey="id", CanBeNull=false, KeyName="fk_menu_resolutions", BackReferenceName="fkmenuresolutionss")]
		public cms_menu fkmenuresolutions { get; set; }

		/// <summary>
		/// fk_user_resolutions
		/// </summary>
		[Association(ThisKey="c_user_id", OtherKey="id", CanBeNull=false, KeyName="fk_user_resolutions", BackReferenceName="fkuserresolutionss")]
		public cms_users fkuserresolutions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_resolutions_templates")]
	public partial class cms_resolutions_templates
	{
		[PrimaryKey, Identity] public int    id           { get; set; } // int
		[Column,     NotNull ] public Guid   f_menu_id    { get; set; } // uniqueidentifier
		[Column,     NotNull ] public string f_user_group { get; set; } // varchar(32)
		[Column,     NotNull ] public bool   b_read       { get; set; } // bit
		[Column,     NotNull ] public bool   b_write      { get; set; } // bit
		[Column,     NotNull ] public bool   b_change     { get; set; } // bit
		[Column,     NotNull ] public bool   b_delete     { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_menu_template_resolutions
		/// </summary>
		[Association(ThisKey="f_menu_id", OtherKey="id", CanBeNull=false, KeyName="fk_menu_template_resolutions", BackReferenceName="fkmenutemplateresolutionss")]
		public cms_menu fkmenutemplateresolutions { get; set; }

		/// <summary>
		/// fk_user_group_resolutions
		/// </summary>
		[Association(ThisKey="f_user_group", OtherKey="c_alias", CanBeNull=false, KeyName="fk_user_group_resolutions", BackReferenceName="fkusergroupresolutionss")]
		public cms_users_group fkusergroupresolutions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_sites")]
	public partial class cms_sites
	{
		[Column,     NotNull    ] public Guid   id               { get; set; } // uniqueidentifier
		[PrimaryKey, NotNull    ] public string c_alias          { get; set; } // varchar(64)
		[Column,     NotNull    ] public string c_name           { get; set; } // nvarchar(512)
		[Column,        Nullable] public string c_name_long      { get; set; } // nvarchar(1024)
		[Column,        Nullable] public string c_adress         { get; set; } // varchar(512)
		[Column,        Nullable] public string c_phone          { get; set; } // varchar(64)
		[Column,        Nullable] public string c_fax            { get; set; } // varchar(64)
		[Column,        Nullable] public string c_email          { get; set; } // varchar(64)
		[Column,        Nullable] public string c_url            { get; set; } // varchar(128)
		[Column,        Nullable] public string c_worktime       { get; set; } // varchar(512)
		[Column,        Nullable] public string c_logo           { get; set; } // varchar(512)
		[Column,        Nullable] public string c_background_img { get; set; } // varchar(512)
		[Column,        Nullable] public Guid?  f_content        { get; set; } // uniqueidentifier
		[Column,        Nullable] public string c_content_type   { get; set; } // varchar(64)
		[Column,        Nullable] public string c_scripts        { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public bool   b_site_off       { get; set; } // bit
		[Column,        Nullable] public string c_facebook       { get; set; } // nvarchar(512)
		[Column,        Nullable] public string c_vk             { get; set; } // nvarchar(512)
		[Column,        Nullable] public string c_instagramm     { get; set; } // nvarchar(512)
		[Column,        Nullable] public string c_odnoklassniki  { get; set; } // nvarchar(512)
		[Column,        Nullable] public string c_twitter        { get; set; } // nvarchar(512)
		[Column,        Nullable] public string c_theme          { get; set; } // nvarchar(256)

		#region Associations

		/// <summary>
		/// fk_sites_domains_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_sites_domains> fksitesdomainss { get; set; }

		/// <summary>
		/// fk_content_sitemap_from_sites_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_sitemap> fkcontentsitemapfromsitess { get; set; }

		/// <summary>
		/// fk_link_site_to_user_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_user_site_link> fklinksitetousers { get; set; }

		/// <summary>
		/// FK_content_banners_cms_sites_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_banners> contentbannerscmssitess { get; set; }

		/// <summary>
		/// FK_site_front_section_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_site_section> sitefrontsections { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_sites_domains")]
	public partial class cms_sites_domains
	{
		[Identity           ] public int    num       { get; set; } // int
		[Column,     NotNull] public Guid   id        { get; set; } // uniqueidentifier
		[Column,     NotNull] public string f_site    { get; set; } // varchar(64)
		[PrimaryKey, NotNull] public string c_domain  { get; set; } // varchar(256)
		[Column,     NotNull] public bool   d_default { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_sites_domains
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="fk_sites_domains", BackReferenceName="fksitesdomainss")]
		public cms_sites fksitesdomains { get; set; }

		#endregion
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_log")]
	public partial class cms_sv_log
	{
		[Column, NotNull    ] public Guid     id            { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid     f_user        { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   c_surname     { get; set; } // nvarchar(128)
		[Column, NotNull    ] public string   c_name        { get; set; } // nvarchar(128)
		[Column,    Nullable] public string   c_patronymic  { get; set; } // nvarchar(128)
		[Column,    Nullable] public string   c_email       { get; set; } // nvarchar(128)
		[Column, NotNull    ] public DateTime d_date        { get; set; } // datetime
		[Column, NotNull    ] public string   f_action      { get; set; } // varchar(32)
		[Column, NotNull    ] public string   c_action_name { get; set; } // varchar(256)
		[Column, NotNull    ] public Guid     f_page        { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   c_ip          { get; set; } // varchar(16)
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_log_users")]
	public partial class cms_sv_log_users
	{
		[Column, NotNull    ] public DateTime d_date         { get; set; } // datetime
		[Column, NotNull    ] public string   f_action       { get; set; } // varchar(32)
		[Column, NotNull    ] public string   c_action_name  { get; set; } // varchar(256)
		[Column,    Nullable] public string   f_site         { get; set; } // varchar(64)
		[Column,    Nullable] public string   f_section      { get; set; } // varchar(64)
		[Column, NotNull    ] public string   c_section_name { get; set; } // varchar(64)
		[Column, NotNull    ] public Guid     f_page         { get; set; } // uniqueidentifier
		[Column,    Nullable] public string   c_page_name    { get; set; } // nvarchar(512)
		[Column, NotNull    ] public Guid     f_user         { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   c_ip           { get; set; } // varchar(16)
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_resolutions")]
	public partial class cms_sv_resolutions
	{
		[Column, NotNull    ] public Guid   c_menu_id    { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string c_title      { get; set; } // nvarchar(128)
		[Column,    Nullable] public string f_group      { get; set; } // varchar(16)
		[Column, NotNull    ] public int    n_permit     { get; set; } // int
		[Column, NotNull    ] public Guid   c_user_id    { get; set; } // uniqueidentifier
		[Column,    Nullable] public string F_UserGroup  { get; set; } // varchar(32)
		[Column, NotNull    ] public string c_surname    { get; set; } // nvarchar(128)
		[Column, NotNull    ] public string c_name       { get; set; } // nvarchar(128)
		[Column,    Nullable] public string c_patronymic { get; set; } // nvarchar(128)
		[Column,    Nullable] public string c_email      { get; set; } // nvarchar(128)
		[Column, NotNull    ] public bool   b_read       { get; set; } // bit
		[Column, NotNull    ] public bool   b_write      { get; set; } // bit
		[Column, NotNull    ] public bool   b_change     { get; set; } // bit
		[Column, NotNull    ] public bool   b_delete     { get; set; } // bit
		[Column, NotNull    ] public bool   b_importent  { get; set; } // bit
		[Column,    Nullable] public string c_class      { get; set; } // varchar(50)
		[Column,    Nullable] public string c_alias      { get; set; } // varchar(16)
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_resolutions_templates")]
	public partial class cms_sv_resolutions_templates
	{
		[Column, NotNull    ] public string c_title           { get; set; } // nvarchar(128)
		[Column, NotNull    ] public int    n_permit          { get; set; } // int
		[Column,    Nullable] public string f_group           { get; set; } // varchar(16)
		[Column, NotNull    ] public string c_user_group_name { get; set; } // varchar(128)
		[Column, NotNull    ] public bool   b_read            { get; set; } // bit
		[Column, NotNull    ] public bool   b_write           { get; set; } // bit
		[Column, NotNull    ] public bool   b_change          { get; set; } // bit
		[Column, NotNull    ] public bool   b_delete          { get; set; } // bit
		[Column, NotNull    ] public string f_user_group      { get; set; } // varchar(32)
		[Column, NotNull    ] public Guid   id                { get; set; } // uniqueidentifier
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_user_sites")]
	public partial class cms_sv_user_sites
	{
		[Column, NotNull] public Guid   f_user { get; set; } // uniqueidentifier
		[Column, NotNull] public string f_site { get; set; } // varchar(64)
		[Column, NotNull] public string c_name { get; set; } // nvarchar(512)
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_users")]
	public partial class cms_sv_users
	{
		[Column, NotNull    ] public Guid      id           { get; set; } // uniqueidentifier
		[Column,    Nullable] public string    c_email      { get; set; } // nvarchar(128)
		[Column,    Nullable] public string    c_salt       { get; set; } // nvarchar(32)
		[Column,    Nullable] public string    c_hash       { get; set; } // nvarchar(128)
		[Column,    Nullable] public string    f_group      { get; set; } // varchar(32)
		[Column, NotNull    ] public string    f_group_name { get; set; } // varchar(128)
		[Column,    Nullable] public string    c_post       { get; set; } // nvarchar(1024)
		[Column, NotNull    ] public string    c_surname    { get; set; } // nvarchar(128)
		[Column, NotNull    ] public string    c_name       { get; set; } // nvarchar(128)
		[Column,    Nullable] public string    c_patronymic { get; set; } // nvarchar(128)
		[Column,    Nullable] public DateTime? d_birthday   { get; set; } // datetime
		[Column, NotNull    ] public bool      b_sex        { get; set; } // bit
		[Column,    Nullable] public string    c_photo      { get; set; } // nvarchar(512)
		[Column,    Nullable] public string    c_adres      { get; set; } // nvarchar(1024)
		[Column,    Nullable] public string    c_phone      { get; set; } // nvarchar(32)
		[Column,    Nullable] public string    c_mobile     { get; set; } // nvarchar(32)
		[Column,    Nullable] public string    c_contacts   { get; set; } // nvarchar(max)
		[Column, NotNull    ] public bool      b_disabled   { get; set; } // bit
	}

	[Table(Schema="dbo", Name="cms_user_site_link")]
	public partial class cms_user_site_link
	{
		[PrimaryKey, NotNull] public Guid   id     { get; set; } // uniqueidentifier
		[Column,     NotNull] public Guid   f_user { get; set; } // uniqueidentifier
		[Column,     NotNull] public string f_site { get; set; } // varchar(64)

		#region Associations

		/// <summary>
		/// fk_link_site_to_user
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="fk_link_site_to_user", BackReferenceName="fklinksitetousers")]
		public cms_sites fklinksitetouser { get; set; }

		/// <summary>
		/// fk_link_user_to_site
		/// </summary>
		[Association(ThisKey="f_user", OtherKey="id", CanBeNull=false, KeyName="fk_link_user_to_site", BackReferenceName="fklinkusertosites")]
		public cms_users fklinkusertosite { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_users")]
	public partial class cms_users
	{
		[PrimaryKey, NotNull    ] public Guid      id                 { get; set; } // uniqueidentifier
		[Column,        Nullable] public string    c_email            { get; set; } // nvarchar(128)
		[Column,        Nullable] public string    c_salt             { get; set; } // nvarchar(32)
		[Column,        Nullable] public string    c_hash             { get; set; } // nvarchar(128)
		[Column,        Nullable] public Guid?     с_change_pass_code { get; set; } // uniqueidentifier
		[Column,        Nullable] public string    f_group            { get; set; } // varchar(32)
		[Column,        Nullable] public string    c_post             { get; set; } // nvarchar(1024)
		[Column,     NotNull    ] public string    c_surname          { get; set; } // nvarchar(128)
		[Column,     NotNull    ] public string    c_name             { get; set; } // nvarchar(128)
		[Column,        Nullable] public string    c_patronymic       { get; set; } // nvarchar(128)
		[Column,        Nullable] public DateTime? d_birthday         { get; set; } // datetime
		[Column,     NotNull    ] public bool      b_sex              { get; set; } // bit
		[Column,        Nullable] public string    c_photo            { get; set; } // nvarchar(512)
		[Column,        Nullable] public string    c_adres            { get; set; } // nvarchar(1024)
		[Column,        Nullable] public string    c_phone            { get; set; } // nvarchar(32)
		[Column,        Nullable] public string    c_mobile           { get; set; } // nvarchar(32)
		[Column,        Nullable] public string    c_contacts         { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public DateTime  d_try_login        { get; set; } // datetime
		[Column,     NotNull    ] public int       n_error_count      { get; set; } // int
		[Column,     NotNull    ] public bool      b_disabled         { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_users_group
		/// </summary>
		[Association(ThisKey="f_group", OtherKey="c_alias", CanBeNull=true, KeyName="fk_users_group", BackReferenceName="fkusersgroups")]
		public cms_users_group fkusersgroup { get; set; }

		/// <summary>
		/// fk_user_resolutions_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="c_user_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_resolutions> fkuserresolutionss { get; set; }

		/// <summary>
		/// fk_link_user_to_site_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_user", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_user_site_link> fklinkusertosites { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_users_group")]
	public partial class cms_users_group
	{
		[Column,     NotNull] public Guid   id      { get; set; } // uniqueidentifier
		[Column,     NotNull] public string c_title { get; set; } // varchar(128)
		[PrimaryKey, NotNull] public string c_alias { get; set; } // varchar(32)
		[Column,     NotNull] public int    n_level { get; set; } // int

		#region Associations

		/// <summary>
		/// fk_users_group_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_users> fkusersgroups { get; set; }

		/// <summary>
		/// fk_user_group_resolutions_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_user_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_resolutions_templates> fkusergroupresolutionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_banner_sections")]
	public partial class content_banner_sections
	{
		[PrimaryKey, NotNull    ] public Guid   id         { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string c_title    { get; set; } // nvarchar(512)
		[Column,        Nullable] public string c_alias    { get; set; } // nvarchar(512)
		[Column,     NotNull    ] public int    n_sort     { get; set; } // int
		[Column,     NotNull    ] public bool   b_disabled { get; set; } // bit
		[Column,     NotNull    ] public int    n_width    { get; set; } // int
		[Column,     NotNull    ] public int    n_height   { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_content_banners_content_banner_sections_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_section", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_banners> contentbannerscontentbannersectionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_banners")]
	public partial class content_banners
	{
		[PrimaryKey, NotNull    ] public Guid     id            { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string   f_site        { get; set; } // varchar(64)
		[Column,     NotNull    ] public string   c_title       { get; set; } // nvarchar(512)
		[Column,        Nullable] public string   c_photo       { get; set; } // nvarchar(1024)
		[Column,        Nullable] public string   c_url         { get; set; } // nvarchar(1024)
		[Column,        Nullable] public string   c_text        { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public DateTime d_date        { get; set; } // datetime
		[Column,     NotNull    ] public int      n_sort        { get; set; } // int
		[Column,     NotNull    ] public bool     b_disabled    { get; set; } // bit
		[Column,     NotNull    ] public Guid     f_section     { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public int      n_count_click { get; set; } // int
		[Column,     NotNull    ] public bool     b_locked      { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK_content_banners_cms_sites
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="FK_content_banners_cms_sites", BackReferenceName="contentbannerscmssitess")]
		public cms_sites contentbannerscmssites { get; set; }

		/// <summary>
		/// FK_content_banners_content_banner_sections
		/// </summary>
		[Association(ThisKey="f_section", OtherKey="id", CanBeNull=false, KeyName="FK_content_banners_content_banner_sections", BackReferenceName="contentbannerscontentbannersectionss")]
		public content_banner_sections contentbannerscontentbannersections { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_content_link")]
	public partial class content_content_link
	{
		[PrimaryKey, NotNull] public Guid   id             { get; set; } // uniqueidentifier
		[Column,     NotNull] public Guid   f_content      { get; set; } // uniqueidentifier
		[Column,     NotNull] public string f_content_type { get; set; } // nvarchar(16)
		[Column,     NotNull] public Guid   f_link         { get; set; } // uniqueidentifier
		[Column,     NotNull] public string f_link_type    { get; set; } // nvarchar(16)
		[Column,     NotNull] public bool   b_origin       { get; set; } // bit
	}

	[Table(Schema="dbo", Name="content_documents")]
	public partial class content_documents
	{
		[PrimaryKey, NotNull    ] public Guid   id          { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string c_title     { get; set; } // varchar(512)
		[Column,        Nullable] public string c_file_path { get; set; } // varchar(1024)
		[Column,     NotNull    ] public Guid   id_page     { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public int    n_sort      { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_content_documents_content_sitemap
		/// </summary>
		[Association(ThisKey="id_page", OtherKey="id", CanBeNull=false, KeyName="FK_content_documents_content_sitemap", BackReferenceName="contentdocumentscontentsitemaps")]
		public content_sitemap contentdocumentscontentsitemap { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_materials")]
	public partial class content_materials
	{
		[PrimaryKey, NotNull    ] public Guid     id                    { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public DateTime d_date                { get; set; } // datetime
		[Column,     NotNull    ] public string   c_title               { get; set; } // varchar(512)
		[Column,        Nullable] public string   c_preview             { get; set; } // varchar(512)
		[Column,        Nullable] public string   c_text                { get; set; } // varchar(max)
		[Column,        Nullable] public string   c_url                 { get; set; } // varchar(1024)
		[Column,        Nullable] public string   c_url_name            { get; set; } // varchar(512)
		[Column,        Nullable] public string   c_desc                { get; set; } // varchar(1024)
		[Column,        Nullable] public string   c_keyw                { get; set; } // varchar(512)
		[Column,     NotNull    ] public int      n_year                { get; set; } // int
		[Column,     NotNull    ] public int      n_month               { get; set; } // int
		[Column,     NotNull    ] public int      n_day                 { get; set; } // int
		[Column,     NotNull    ] public string   c_alias               { get; set; } // varchar(512)
		[Column,     NotNull    ] public bool     b_disabled            { get; set; } // bit
		[Column,     NotNull    ] public bool     b_important           { get; set; } // bit
		[Column,     NotNull    ] public Guid     f_content_origin      { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string   c_content_type_origin { get; set; } // varchar(64)
		[Column,     NotNull    ] public bool     b_locked              { get; set; } // bit
		[Column,     NotNull    ] public int      n_count_see           { get; set; } // int
		[Column,        Nullable] public string   c_preview_source      { get; set; } // varchar(128)
		[Column,        Nullable] public int?     n_old_id              { get; set; } // int

		#region Associations

		/// <summary>
		/// fk_content_materials_groups_link_material_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_material", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_materials_groups_link> fkcontentmaterialsgroupslinkmaterials { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_materials_groups")]
	public partial class content_materials_groups
	{
		[PrimaryKey, NotNull    ] public Guid   id      { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string c_title { get; set; } // nvarchar(256)
		[Column,     NotNull    ] public int    n_sort  { get; set; } // int
		[Column,        Nullable] public string c_alias { get; set; } // nvarchar(256)

		#region Associations

		/// <summary>
		/// fk_content_materials_groups_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_materials_groups_link> fkcontentmaterialsgroupss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_materials_groups_link")]
	public partial class content_materials_groups_link
	{
		[PrimaryKey, NotNull] public Guid id         { get; set; } // uniqueidentifier
		[Column,     NotNull] public Guid f_material { get; set; } // uniqueidentifier
		[Column,     NotNull] public Guid f_group    { get; set; } // uniqueidentifier

		#region Associations

		/// <summary>
		/// fk_content_materials_groups
		/// </summary>
		[Association(ThisKey="f_group", OtherKey="id", CanBeNull=false, KeyName="fk_content_materials_groups", BackReferenceName="fkcontentmaterialsgroupss")]
		public content_materials_groups fkcontentmaterialsgroups { get; set; }

		/// <summary>
		/// fk_content_materials_groups_link_material
		/// </summary>
		[Association(ThisKey="f_material", OtherKey="id", CanBeNull=false, KeyName="fk_content_materials_groups_link_material", BackReferenceName="fkcontentmaterialsgroupslinkmaterials")]
		public content_materials fkcontentmaterialsgroupslinkmaterial { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_photoalbum")]
	public partial class content_photoalbum
	{
		[PrimaryKey, NotNull    ] public Guid     id         { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string   c_title    { get; set; } // varchar(512)
		[Column,        Nullable] public string   c_preview  { get; set; } // varchar(512)
		[Column,        Nullable] public string   c_text     { get; set; } // varchar(max)
		[Column,     NotNull    ] public DateTime d_date     { get; set; } // datetime
		[Column,     NotNull    ] public string   f_site     { get; set; } // varchar(64)
		[Column,        Nullable] public string   c_path     { get; set; } // varchar(1024)
		[Column,     NotNull    ] public bool     c_disabled { get; set; } // bit
		[Column,        Nullable] public int?     n_old_id   { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_content_photos_content_photoalbum_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_album", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_photos> contentphotoscontentphotoalbums { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_photos")]
	public partial class content_photos
	{
		[PrimaryKey, NotNull] public Guid     id        { get; set; } // uniqueidentifier
		[Column,     NotNull] public Guid     f_album   { get; set; } // uniqueidentifier
		[Column,     NotNull] public string   c_title   { get; set; } // varchar(512)
		[Column,     NotNull] public DateTime d_date    { get; set; } // datetime
		[Column,     NotNull] public string   c_preview { get; set; } // varchar(512)
		[Column,     NotNull] public string   c_photo   { get; set; } // varchar(512)
		[Column,     NotNull] public int      n_sort    { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_content_photos_content_photoalbum
		/// </summary>
		[Association(ThisKey="f_album", OtherKey="id", CanBeNull=false, KeyName="FK_content_photos_content_photoalbum", BackReferenceName="contentphotoscontentphotoalbums")]
		public content_photoalbum contentphotoscontentphotoalbum { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_sitemap")]
	public partial class content_sitemap
	{
		[PrimaryKey, NotNull    ] public Guid   id              { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string f_site          { get; set; } // varchar(64)
		[Column,     NotNull    ] public string f_front_section { get; set; } // varchar(64)
		[Column,     NotNull    ] public string c_path          { get; set; } // varchar(1024)
		[Column,        Nullable] public string c_alias         { get; set; } // varchar(64)
		[Column,        Nullable] public string c_title         { get; set; } // nvarchar(256)
		[Column,        Nullable] public string c_preview       { get; set; } // varchar(1024)
		[Column,        Nullable] public string c_url           { get; set; } // varchar(1024)
		[Column,        Nullable] public string c_text          { get; set; } // nvarchar(max)
		[Column,        Nullable] public string c_desc          { get; set; } // nvarchar(1024)
		[Column,        Nullable] public string c_keyw          { get; set; } // nvarchar(512)
		[Column,     NotNull    ] public bool   b_disabled      { get; set; } // bit
		[Column,     NotNull    ] public bool   b_disabled_menu { get; set; } // bit
		/// <summary>
		/// сортировка
		/// </summary>
		[Column,     NotNull    ] public int    n_sort          { get; set; } // int
		[Column,        Nullable] public Guid?  uui_parent      { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public bool   b_blocked       { get; set; } // bit
		[Column,        Nullable] public string c_photo         { get; set; } // nvarchar(1024)
		[Column,        Nullable] public int?   n_old_id        { get; set; } // int

		#region Associations

		/// <summary>
		/// fk_content_sitemap_from_sites
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="fk_content_sitemap_from_sites", BackReferenceName="fkcontentsitemapfromsitess")]
		public cms_sites fkcontentsitemapfromsites { get; set; }

		/// <summary>
		/// fk_content_sitemap_front_section
		/// </summary>
		[Association(ThisKey="f_front_section", OtherKey="c_alias", CanBeNull=false, KeyName="fk_content_sitemap_front_section", BackReferenceName="fkcontentsitemapfrontsections")]
		public front_section fkcontentsitemapfrontsection { get; set; }

		/// <summary>
		/// FK_content_documents_content_sitemap_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="id_page", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_documents> contentdocumentscontentsitemaps { get; set; }

		/// <summary>
		/// FK_content_sitemap_menutypes_content_sitemap_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_sitemap", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_sitemap_menutypes> contentsitemapmenutypescontentsitemaps { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_sitemap_menus")]
	public partial class content_sitemap_menus
	{
		[PrimaryKey, NotNull    ] public Guid   id          { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string c_title     { get; set; } // nvarchar(256)
		[Column,     NotNull    ] public int    n_sort      { get; set; } // int
		[Column,        Nullable] public string c_alias     { get; set; } // nvarchar(256)
		[Column,     NotNull    ] public bool   b_available { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK_content_sitemap_menutypes_content_sitemap_menus_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_menutype", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_sitemap_menutypes> contentsitemapmenutypescontentsitemapmenuss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_sitemap_menutypes")]
	public partial class content_sitemap_menutypes
	{
		[Column, NotNull] public Guid   f_sitemap  { get; set; } // uniqueidentifier
		[Column, NotNull] public Guid   f_menutype { get; set; } // uniqueidentifier
		[Column, NotNull] public string f_site     { get; set; } // varchar(64)
		[Column, NotNull] public int    n_sort     { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_content_sitemap_menutypes_content_sitemap_menus
		/// </summary>
		[Association(ThisKey="f_menutype", OtherKey="id", CanBeNull=false, KeyName="FK_content_sitemap_menutypes_content_sitemap_menus", BackReferenceName="contentsitemapmenutypescontentsitemapmenuss")]
		public content_sitemap_menus contentsitemapmenutypescontentsitemapmenus { get; set; }

		/// <summary>
		/// FK_content_sitemap_menutypes_content_sitemap
		/// </summary>
		[Association(ThisKey="f_sitemap", OtherKey="id", CanBeNull=false, KeyName="FK_content_sitemap_menutypes_content_sitemap", BackReferenceName="contentsitemapmenutypescontentsitemaps")]
		public content_sitemap contentsitemapmenutypescontentsitemap { get; set; }

		#endregion
	}

	// View
	[Table(Schema="dbo", Name="content_sv_banner_sections_sites")]
	public partial class content_sv_banner_sections_sites
	{
		[Column, NotNull] public string domain     { get; set; } // varchar(64)
		[Column, NotNull] public string site_name  { get; set; } // nvarchar(512)
		[Column, NotNull] public Guid   section_id { get; set; } // uniqueidentifier
	}

	// View
	[Table(Schema="dbo", Name="content_sv_banners_section")]
	public partial class content_sv_banners_section
	{
		[Column, NotNull    ] public Guid     id         { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   f_site     { get; set; } // varchar(64)
		[Column, NotNull    ] public string   c_title    { get; set; } // nvarchar(512)
		[Column,    Nullable] public string   c_photo    { get; set; } // nvarchar(1024)
		[Column,    Nullable] public string   c_url      { get; set; } // nvarchar(1024)
		[Column,    Nullable] public string   c_text     { get; set; } // nvarchar(max)
		[Column, NotNull    ] public DateTime d_date     { get; set; } // datetime
		[Column, NotNull    ] public int      n_sort     { get; set; } // int
		[Column, NotNull    ] public bool     b_disabled { get; set; } // bit
		[Column, NotNull    ] public Guid     f_section  { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid     Expr2      { get; set; } // uniqueidentifier
		[Column,    Nullable] public string   c_alias    { get; set; } // nvarchar(512)
	}

	// View
	[Table(Schema="dbo", Name="content_sv_materials_groups")]
	public partial class content_sv_materials_groups
	{
		[Column, NotNull    ] public Guid     id          { get; set; } // uniqueidentifier
		[Column, NotNull    ] public DateTime d_date      { get; set; } // datetime
		[Column, NotNull    ] public string   c_title     { get; set; } // varchar(512)
		[Column,    Nullable] public string   c_preview   { get; set; } // varchar(512)
		[Column,    Nullable] public string   c_text      { get; set; } // varchar(max)
		[Column,    Nullable] public string   c_url       { get; set; } // varchar(1024)
		[Column,    Nullable] public string   c_url_name  { get; set; } // varchar(512)
		[Column,    Nullable] public string   c_desc      { get; set; } // varchar(1024)
		[Column,    Nullable] public string   c_keyw      { get; set; } // varchar(512)
		[Column, NotNull    ] public int      n_year      { get; set; } // int
		[Column, NotNull    ] public int      n_month     { get; set; } // int
		[Column, NotNull    ] public int      n_day       { get; set; } // int
		[Column, NotNull    ] public string   c_alias     { get; set; } // varchar(512)
		[Column, NotNull    ] public bool     b_disabled  { get; set; } // bit
		[Column, NotNull    ] public bool     b_important { get; set; } // bit
		[Column, NotNull    ] public Guid     group_id    { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   group_title { get; set; } // nvarchar(256)
		[Column,    Nullable] public string   group_alias { get; set; } // nvarchar(256)
	}

	// View
	[Table(Schema="dbo", Name="content_sv_materials_groups_for_site")]
	public partial class content_sv_materials_groups_for_site
	{
		[Column, NotNull    ] public string c_title { get; set; } // nvarchar(256)
		[Column,    Nullable] public string c_alias { get; set; } // nvarchar(256)
		[Column, NotNull    ] public string domain  { get; set; } // varchar(64)
		[Column, NotNull    ] public int    n_sort  { get; set; } // int
	}

	// View
	[Table(Schema="dbo", Name="content_sv_materials_sites")]
	public partial class content_sv_materials_sites
	{
		[Column, NotNull    ] public Guid     id          { get; set; } // uniqueidentifier
		[Column, NotNull    ] public DateTime d_date      { get; set; } // datetime
		[Column, NotNull    ] public string   c_title     { get; set; } // varchar(512)
		[Column,    Nullable] public string   c_preview   { get; set; } // varchar(512)
		[Column,    Nullable] public string   c_text      { get; set; } // varchar(max)
		[Column,    Nullable] public string   c_url       { get; set; } // varchar(1024)
		[Column,    Nullable] public string   c_url_name  { get; set; } // varchar(512)
		[Column,    Nullable] public string   c_desc      { get; set; } // varchar(1024)
		[Column,    Nullable] public string   c_keyw      { get; set; } // varchar(512)
		[Column, NotNull    ] public int      n_year      { get; set; } // int
		[Column, NotNull    ] public int      n_month     { get; set; } // int
		[Column, NotNull    ] public int      n_day       { get; set; } // int
		[Column, NotNull    ] public string   c_alias     { get; set; } // varchar(512)
		[Column, NotNull    ] public bool     b_disabled  { get; set; } // bit
		[Column, NotNull    ] public bool     b_important { get; set; } // bit
		[Column, NotNull    ] public string   domain      { get; set; } // varchar(64)
	}

	// View
	[Table(Schema="dbo", Name="content_sv_orgs_by_type")]
	public partial class content_sv_orgs_by_type
	{
		[Column, NotNull] public Guid   id      { get; set; } // uniqueidentifier
		[Column, NotNull] public string c_title { get; set; } // nvarchar(512)
		[Column, NotNull] public int    n_sort  { get; set; } // int
		[Column, NotNull] public Guid   f_type  { get; set; } // uniqueidentifier
	}

	// View
	[Table(Schema="dbo", Name="content_sv_orgs_not_attached")]
	public partial class content_sv_orgs_not_attached
	{
		[Column, NotNull] public Guid   id      { get; set; } // uniqueidentifier
		[Column, NotNull] public string c_title { get; set; } // nvarchar(512)
	}

	// View
	[Table(Schema="dbo", Name="content_sv_people_department")]
	public partial class content_sv_people_department
	{
		[Column, NotNull    ] public Guid      f_department { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid      id           { get; set; } // uniqueidentifier
		[Column,    Nullable] public string    c_surname    { get; set; } // varchar(64)
		[Column,    Nullable] public string    c_name       { get; set; } // varchar(64)
		[Column,    Nullable] public string    c_patronymic { get; set; } // varchar(64)
		[Column,    Nullable] public DateTime? d_birthdate  { get; set; } // datetime2(7)
		[Column, NotNull    ] public string    c_snils      { get; set; } // char(11)
		[Column, NotNull    ] public bool      b_deleted    { get; set; } // bit
		[Column,    Nullable] public string    c_status     { get; set; } // varchar(128)
		[Column,    Nullable] public string    c_post       { get; set; } // varchar(128)
		[Column, NotNull    ] public Guid      idOrgLink    { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid      f_people     { get; set; } // uniqueidentifier
		[Column,    Nullable] public string    c_photo      { get; set; } // varchar(max)
	}

	// View
	[Table(Schema="dbo", Name="content_sv_people_front")]
	public partial class content_sv_people_front
	{
		[Column, NotNull    ] public Guid   id           { get; set; } // uniqueidentifier
		[Column,    Nullable] public string fio          { get; set; } // varchar(194)
		[Column, NotNull    ] public string c_snils      { get; set; } // char(11)
		[Column,    Nullable] public Guid?  f_department { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string c_name       { get; set; } // nvarchar(512)
		[Column, NotNull    ] public string c_alias      { get; set; } // varchar(64)
		[Column, NotNull    ] public bool   b_doctor     { get; set; } // bit
		[Column, NotNull    ] public int    f_post       { get; set; } // int
		[Column,    Nullable] public string c_photo      { get; set; } // nvarchar(1024)
	}

	// View
	[Table(Schema="dbo", Name="content_sv_people_org")]
	public partial class content_sv_people_org
	{
		[Column, NotNull    ] public Guid   id           { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid   PeopleId     { get; set; } // uniqueidentifier
		[Column,    Nullable] public string c_surname    { get; set; } // varchar(64)
		[Column,    Nullable] public string c_name       { get; set; } // varchar(64)
		[Column,    Nullable] public string c_patronymic { get; set; } // varchar(64)
		[Column, NotNull    ] public Guid   f_org        { get; set; } // uniqueidentifier
	}

	// View
	[Table(Schema="dbo", Name="content_sv_sitemap_menu")]
	public partial class content_sv_sitemap_menu
	{
		[Column, NotNull    ] public Guid   id              { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string f_site          { get; set; } // varchar(64)
		[Column, NotNull    ] public string f_front_section { get; set; } // nvarchar(16)
		[Column, NotNull    ] public string c_path          { get; set; } // varchar(1024)
		[Column,    Nullable] public string c_alias         { get; set; } // varchar(64)
		[Column,    Nullable] public string c_title         { get; set; } // nvarchar(256)
		[Column,    Nullable] public string c_preview       { get; set; } // varchar(1024)
		[Column,    Nullable] public string c_url           { get; set; } // varchar(1024)
		[Column,    Nullable] public string c_text          { get; set; } // nvarchar(max)
		[Column,    Nullable] public string c_desc          { get; set; } // nvarchar(1024)
		[Column,    Nullable] public string c_keyw          { get; set; } // nvarchar(512)
		[Column, NotNull    ] public bool   b_disabled      { get; set; } // bit
		[Column, NotNull    ] public bool   b_blocked       { get; set; } // bit
		[Column, NotNull    ] public bool   b_disabled_menu { get; set; } // bit
		[Column, NotNull    ] public int    n_sort          { get; set; } // int
		[Column,    Nullable] public Guid?  uui_parent      { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string menu_title      { get; set; } // nvarchar(256)
		[Column, NotNull    ] public int    menu_sort       { get; set; } // int
		[Column, NotNull    ] public Guid   f_menutype      { get; set; } // uniqueidentifier
		[Column,    Nullable] public string menu_alias      { get; set; } // nvarchar(256)
		[Column,    Nullable] public string c_photo         { get; set; } // nvarchar(1024)
	}

	[Table(Schema="dbo", Name="front_modules")]
	public partial class front_modules
	{
		[PrimaryKey, NotNull] public Guid   id           { get; set; } // uniqueidentifier
		[Column,     NotNull] public string c_name       { get; set; } // nvarchar(512)
		[Column,     NotNull] public string f_size       { get; set; } // varchar(16)
		[Column,     NotNull] public string f_type       { get; set; } // varchar(64)
		[Column,     NotNull] public string c_alias      { get; set; } // nvarchar(16)
		[Column,     NotNull] public string c_controller { get; set; } // nvarchar(32)
		[Column,     NotNull] public string c_action     { get; set; } // nvarchar(32)
		[Column,     NotNull] public string c_url        { get; set; } // nvarchar(512)

		#region Associations

		/// <summary>
		/// FK_module_section
		/// </summary>
		[Association(ThisKey="f_type", OtherKey="c_alias", CanBeNull=false, KeyName="FK_module_section", BackReferenceName="modulesections")]
		public front_section modulesection { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="front_page_views")]
	public partial class front_page_views
	{
		[PrimaryKey, NotNull    ] public Guid   id          { get; set; } // uniqueidentifier
		[Column,        Nullable] public string f_site      { get; set; } // varchar(64)
		[Column,     NotNull    ] public string c_title     { get; set; } // nvarchar(256)
		[Column,        Nullable] public string f_page_type { get; set; } // varchar(64)
		[Column,     NotNull    ] public string c_url       { get; set; } // varchar(1024)
		[Column,     NotNull    ] public int    n_sort      { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_site_front_section_page_views_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_page_view", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_site_section> sitefrontsectionpageviewss { get; set; }

		/// <summary>
		/// FK_front_section_default_page_views_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="c_default_view", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_section> frontsectiondefaultpageviewss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="front_section")]
	public partial class front_section
	{
		[Column,     NotNull] public Guid   id             { get; set; } // uniqueidentifier
		[Column,     NotNull] public string c_name         { get; set; } // varchar(128)
		[PrimaryKey, NotNull] public string c_alias        { get; set; } // varchar(64)
		[Column,     NotNull] public Guid   c_default_view { get; set; } // uniqueidentifier

		#region Associations

		/// <summary>
		/// FK_front_section_default_page_views
		/// </summary>
		[Association(ThisKey="c_default_view", OtherKey="id", CanBeNull=false, KeyName="FK_front_section_default_page_views", BackReferenceName="frontsectiondefaultpageviewss")]
		public front_page_views frontsectiondefaultpageviews { get; set; }

		/// <summary>
		/// FK_module_section_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_type", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_modules> modulesections { get; set; }

		/// <summary>
		/// fk_content_sitemap_front_section_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_front_section", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_sitemap> fkcontentsitemapfrontsections { get; set; }

		/// <summary>
		/// FK_front_section_site_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_front_section", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_site_section> frontsectionsites { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="front_site_section")]
	public partial class front_site_section
	{
		[Column, NotNull] public string f_site          { get; set; } // varchar(64)
		[Column, NotNull] public string f_front_section { get; set; } // varchar(64)
		[Column, NotNull] public Guid   f_page_view     { get; set; } // uniqueidentifier

		#region Associations

		/// <summary>
		/// FK_site_front_section_page_views
		/// </summary>
		[Association(ThisKey="f_page_view", OtherKey="id", CanBeNull=false, KeyName="FK_site_front_section_page_views", BackReferenceName="sitefrontsectionpageviewss")]
		public front_page_views sitefrontsectionpageviews { get; set; }

		/// <summary>
		/// FK_front_section_site
		/// </summary>
		[Association(ThisKey="f_front_section", OtherKey="c_alias", CanBeNull=false, KeyName="FK_front_section_site", BackReferenceName="frontsectionsites")]
		public front_section frontsectionsite { get; set; }

		/// <summary>
		/// FK_site_front_section
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="FK_site_front_section", BackReferenceName="sitefrontsections")]
		public cms_sites sitefrontsection { get; set; }

		#endregion
	}

	// View
	[Table(Schema="dbo", Name="front_sv_page_veiw")]
	public partial class front_sv_page_veiw
	{
		[Column, NotNull    ] public string Expr1       { get; set; } // varchar(64)
		[Column, NotNull    ] public string c_title     { get; set; } // nvarchar(256)
		[Column,    Nullable] public string f_pege_type { get; set; } // varchar(16)
		[Column, NotNull    ] public string c_name      { get; set; } // varchar(128)
		[Column, NotNull    ] public string c_url       { get; set; } // varchar(1024)
		[Column, NotNull    ] public string f_site      { get; set; } // varchar(64)
	}

	// View
	[Table(Schema="dbo", Name="sv_orgs_materials")]
	public partial class sv_orgs_materials
	{
		[Column, NotNull    ] public Guid     link_material           { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid     link_site               { get; set; } // uniqueidentifier
		[Column, NotNull    ] public bool     link_origin             { get; set; } // bit
		[Column, NotNull    ] public Guid     material_id             { get; set; } // uniqueidentifier
		[Column, NotNull    ] public DateTime material_date           { get; set; } // datetime
		[Column, NotNull    ] public string   material_title          { get; set; } // varchar(512)
		[Column,    Nullable] public string   material_preview        { get; set; } // varchar(512)
		[Column,    Nullable] public string   material_text           { get; set; } // varchar(max)
		[Column,    Nullable] public string   material_url            { get; set; } // varchar(1024)
		[Column,    Nullable] public string   material_url_name       { get; set; } // varchar(512)
		[Column,    Nullable] public string   material_desc           { get; set; } // varchar(1024)
		[Column,    Nullable] public string   material_keyw           { get; set; } // varchar(512)
		[Column, NotNull    ] public int      material_year           { get; set; } // int
		[Column, NotNull    ] public int      material_month          { get; set; } // int
		[Column, NotNull    ] public int      material_day            { get; set; } // int
		[Column, NotNull    ] public string   material_alias          { get; set; } // varchar(512)
		[Column, NotNull    ] public bool     material_disabled       { get; set; } // bit
		[Column, NotNull    ] public bool     material_important      { get; set; } // bit
		[Column, NotNull    ] public bool     material_locked         { get; set; } // bit
		[Column, NotNull    ] public int      material_clicks         { get; set; } // int
		[Column,    Nullable] public string   material_preview_source { get; set; } // varchar(128)
		[Column, NotNull    ] public Guid     org_id                  { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   org_title               { get; set; } // nvarchar(512)
		[Column,    Nullable] public string   org_title_short         { get; set; } // nvarchar(512)
		[Column, NotNull    ] public Guid     site_id                 { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   site_alias              { get; set; } // varchar(64)
		[Column, NotNull    ] public string   site_name               { get; set; } // nvarchar(512)
		[Column, NotNull    ] public bool     site_off                { get; set; } // bit
	}

	// View
	[Table(Schema="dbo", Name="sv_sites_banners")]
	public partial class sv_sites_banners
	{
		[Column, NotNull    ] public Guid     link_banner        { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid     link_site          { get; set; } // uniqueidentifier
		[Column, NotNull    ] public bool     link_origin        { get; set; } // bit
		[Column, NotNull    ] public Guid     banner_id          { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   banner_origin_site { get; set; } // varchar(64)
		[Column, NotNull    ] public string   banner_title       { get; set; } // nvarchar(512)
		[Column,    Nullable] public string   banner_image       { get; set; } // nvarchar(1024)
		[Column,    Nullable] public string   banner_url         { get; set; } // nvarchar(1024)
		[Column,    Nullable] public string   banner_text        { get; set; } // nvarchar(max)
		[Column, NotNull    ] public DateTime banner_date        { get; set; } // datetime
		[Column, NotNull    ] public int      banner_sort        { get; set; } // int
		[Column, NotNull    ] public bool     banner_disabled    { get; set; } // bit
		[Column, NotNull    ] public Guid     banner_section     { get; set; } // uniqueidentifier
		[Column, NotNull    ] public int      banner_clicks      { get; set; } // int
		[Column, NotNull    ] public bool     banner_locked      { get; set; } // bit
		[Column, NotNull    ] public Guid     site_id            { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   site_alias         { get; set; } // varchar(64)
		[Column, NotNull    ] public string   site_name          { get; set; } // nvarchar(512)
		[Column, NotNull    ] public bool     site_off           { get; set; } // bit
		[Column,    Nullable] public string   section_alias      { get; set; } // nvarchar(512)
	}

	public static partial class CMSdbStoredProcedures
	{
		#region dublicate_content_sitemap

		public static int dublicate_content_sitemap(this DataConnection dataConnection, string @domain, string @new_domain)
		{
			return dataConnection.ExecuteProc("[dbo].[dublicate_content_sitemap]",
				new DataParameter("@domain",     @domain,     DataType.VarChar),
				new DataParameter("@new_domain", @new_domain, DataType.VarChar));
		}

		#endregion

		#region sp_alterdiagram

		public static int sp_alterdiagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32),
				new DataParameter("@version",     @version,     DataType.Int32),
				new DataParameter("@definition",  @definition,  DataType.VarBinary));
		}

		#endregion

		#region sp_creatediagram

		public static int sp_creatediagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32),
				new DataParameter("@version",     @version,     DataType.Int32),
				new DataParameter("@definition",  @definition,  DataType.VarBinary));
		}

		#endregion

		#region sp_dropdiagram

		public static int sp_dropdiagram(this DataConnection dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32));
		}

		#endregion

		#region sp_helpdiagramdefinition

		public static IEnumerable<sp_helpdiagramdefinitionResult> sp_helpdiagramdefinition(this DataConnection dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.QueryProc<sp_helpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32));
		}

		public partial class sp_helpdiagramdefinitionResult
		{
			public int?   version    { get; set; }
			public byte[] definition { get; set; }
		}

		#endregion

		#region sp_helpdiagrams

		public static IEnumerable<sp_helpdiagramsResult> sp_helpdiagrams(this DataConnection dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.QueryProc<sp_helpdiagramsResult>("[dbo].[sp_helpdiagrams]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32));
		}

		public partial class sp_helpdiagramsResult
		{
			public string Database { get; set; }
			public string Name     { get; set; }
			public int    ID       { get; set; }
			public string Owner    { get; set; }
			public int    OwnerID  { get; set; }
		}

		#endregion

		#region sp_renamediagram

		public static int sp_renamediagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, string @new_diagramname)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]",
				new DataParameter("@diagramname",     @diagramname,     DataType.NVarChar),
				new DataParameter("@owner_id",        @owner_id,        DataType.Int32),
				new DataParameter("@new_diagramname", @new_diagramname, DataType.NVarChar));
		}

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region fn_diagramobjects

		[Sql.Function(Name="dbo.fn_diagramobjects", ServerSideOnly=true)]
		public static int? fn_diagramobjects()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static cms_log Find(this ITable<cms_log> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_log_actions Find(this ITable<cms_log_actions> table, string c_action)
		{
			return table.FirstOrDefault(t =>
				t.c_action == c_action);
		}

		public static cms_log_sections Find(this ITable<cms_log_sections> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static cms_menu Find(this ITable<cms_menu> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_menu_group Find(this ITable<cms_menu_group> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static cms_resolutions Find(this ITable<cms_resolutions> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_resolutions_templates Find(this ITable<cms_resolutions_templates> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_sites Find(this ITable<cms_sites> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static cms_sites_domains Find(this ITable<cms_sites_domains> table, string c_domain)
		{
			return table.FirstOrDefault(t =>
				t.c_domain == c_domain);
		}

		public static cms_user_site_link Find(this ITable<cms_user_site_link> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_users Find(this ITable<cms_users> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_users_group Find(this ITable<cms_users_group> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static content_banner_sections Find(this ITable<content_banner_sections> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_banners Find(this ITable<content_banners> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_content_link Find(this ITable<content_content_link> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_documents Find(this ITable<content_documents> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_materials Find(this ITable<content_materials> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_materials_groups Find(this ITable<content_materials_groups> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_materials_groups_link Find(this ITable<content_materials_groups_link> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_photoalbum Find(this ITable<content_photoalbum> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_photos Find(this ITable<content_photos> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_sitemap Find(this ITable<content_sitemap> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_sitemap_menus Find(this ITable<content_sitemap_menus> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static front_modules Find(this ITable<front_modules> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static front_page_views Find(this ITable<front_page_views> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static front_section Find(this ITable<front_section> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}
	}
}
 